### ISSUE TITLE
problem install in socket io 

### ISSUE THREAD

**Issue by neenekrasov** [cagataycali/tick.chat#10]
console browser
uild.js?a270:1 GET http://127.0.0.1:3000/socket.io/?EIO=3&transport=polling&t=MxLF03K net::ERR_CONNECTION_REFUSED

log server

0|dev-serv |  DONE  Compiled successfully in 787ms9:53:19 AM
0|dev-serv | 
0|dev-serv |  WAIT  Compiling...9:58:35 AM
0|dev-serv | 
0|dev-serv |  DONE  Compiled successfully in 211ms9:58:36 AM
0|dev-serv | 
0|dev-serv |  WAIT  Compiling...9:59:09 AM
0|dev-serv | 
0|dev-serv |  DONE  Compiled successfully in 96ms9:59:10 AM
0|dev-serv | 
0|dev-serv | > Starting dev server...
0|dev-serv |  DONE  Compiled successfully in 12490ms9:59:46 AM
0|dev-serv | 
0|dev-serv | > Listening at http://localhost:8080
0|dev-serv | 

/root/.pm2/logs/dev-server-error.log last 15 lines:
0|dev-serv |     at ChildProcess.<anonymous> (/srv/node_modules/opn/index.js:83:13)
0|dev-serv |     at Object.onceWrapper (events.js:309:26)
0|dev-serv |     at ChildProcess.emit (events.js:219:5)
0|dev-serv |     at maybeClose (internal/child_process.js:1027:16)
0|dev-serv |     at Socket.<anonymous> (internal/child_process.js:442:11)
0|dev-serv |     at Socket.emit (events.js:219:5)
0|dev-serv |     at Pipe.<anonymous> (net.js:666:12)
0|dev-serv | Error: Exited with code 3
0|dev-serv |     at ChildProcess.<anonymous> (/srv/node_modules/opn/index.js:83:13)
0|dev-serv |     at Object.onceWrapper (events.js:309:26)
0|dev-serv |     at ChildProcess.emit (events.js:219:5)
0|dev-serv |     at maybeClose (internal/child_process.js:1027:16)
0|dev-serv |     at Socket.<anonymous> (internal/child_process.js:442:11)
0|dev-serv |     at Socket.emit (events.js:219:5)
0|dev-serv |     at Pipe.<anonymous> (net.js:666:12)

**Comment by neenekrasov** [comment]
as I understand the server does not see socket.io (127.0.0.1: 3000)

**Comment by cagataycali** [comment]
How can I reproduce this issue?

Because the code can run without any modification on heroku with one click deploy option.

**Comment by cagataycali** [comment]
I'v just removed socket.io origin check.

Use this steps for running locally;

```bash
git clone git@github.com:cagataycali/tick.chat.git && cd tick.chat;
npm install;
npm start;
# Another terminal session
cd server;
npm install;
npm start;
```

**Comment by neenekrasov** [comment]
experiencing difficulty with installing on vps and configuring nginx as at startup it can not find socket.io (127.0.0.1: 3000)

**Comment by cagataycali** [comment]
You can try external ip example, your ip might be 85.xx.xx.xx:3000
