### ISSUE TITLE
Localization of Time

### ISSUE THREAD

**Issue by MaSven** [cagataycali/tick.chat#7]
When iam joining a chat, the time is not right for my timezone. Iam in UTC+2 but the time is in UTC+3.

Firefox 55.03 64 bit Windows 10.

**Comment by cagataycali** [comment]
This is a different problem, I show the clock when you receive the message, but any screen capture for this might be good

**Comment by MaSven** [comment]
![grafik](https://user-images.githubusercontent.com/9138252/30698544-8f7da3e4-9ee2-11e7-8ea6-f3ce9c05a1a7.png)
His time is in UTC+3 i guess and mine is in UTC+2 wouldnt it be better if i can see the time in UTC+2? Because so i can see how much time went on from the last message.

**Comment by cagataycali** [comment]
How about how many seconds have passed from the last message? Like as 5 seconds ago

**Comment by MaSven** [comment]
that would also be cool. But i think displaying time in the same timezone is saner than having the user to remember how many hours the other user is behing him or otherwise.
